name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test

    #   - name: Send email notification
    #     uses: dawidd6/action-send-mail@v3
    #     with:
    #       server_address: smtp.gmail.com
    #       server_port: 587
    #       username: ${{ secrets.EMAIL_USERNAME }}
    #       password: ${{ secrets.EMAIL_PASSWORD }}
    #       subject: CI Pipeline - ${{ github.repository }}
    #       body: Build ${{ github.run_number }} - ${{ github.workflow }}: ${{ job.status }}
    #       to: cesarprandosz@gmail.com

  
